export const COMISIONES_POR_CUENTA = {
  'bancamiga': 5,
  'venezuela': 2.5,
  'bolivares_bs': 0,
  'efectivo': 0,
  'zelle': 0,
  'binance': 0,
  'zinli': 0,
  'paypal': 0,
  'bnc': 1.5,
  'bnc papa': 1.5,
  'banco bnc': 1.5,
  'banco venezuela': 2.5,
  'banco de venezuela': 2.5,
};
